blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/chiba233/yumeDSL/discussions
    about: Ask questions, share ideas, or discuss usage in GitHub Discussions.
